services:
  ros-gui:
    build: .
    container_name: ros-jazzy-gui-container
    privileged: true
    ports:
      - "5900:5900"  # SPICE port
    environment:
      - SPICE_PASSWORD=password
      - DISPLAY=:1
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    networks: [rosnet]
    stdin_open: true
    tty: true
    shm_size: 2g
    volumes:
      - wallpaper_vol:/usr/share/backgrounds/custom
      - ./src:/root/ros_ws/src  # Mount your ROS2 workspace source
    working_dir: /root/ros_ws
 
volumes:
  wallpaper_vol:

networks:
  rosnet:
    driver: bridge