services:
  xserver:
    image: consol/ubuntu-xfce-vnc
    container_name: xserver-vnc
    ports:
      - "5901:5901"  # VNC port
      - "6901:6901"  # noVNC web client
    environment:
      - VNC_PW=password
    shm_size: 2g
    networks: [rosnet]

  ros:
    image: ros-jazzy-dev
    container_name: ros-jazzy-container
    privileged: true
    environment:
      - DISPLAY=xserver:0.0
      - QT_X11_NO_MITSHM=1
    devices:
      - /dev/dri:/dev/dri
    networks: [rosnet]
    depends_on:
      - xserver
    stdin_open: true
    tty: true

networks:
  rosnet:
    driver: bridge
